// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicQuery: typeof import('./components/Table/src/BasicQuery.vue')['default']
    BasicTable: typeof import('./components/Table/src/BasicTable.vue')['default']
    CheckboxGroup: typeof import('./components/Form/src/components/CheckboxGroup.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor/src/CodeEditor.vue')['default']
    Cropper: typeof import('./components/Cropper/src/Cropper.vue')['default']
    Drawer: typeof import('./components/Drawer/src/Drawer.vue')['default']
    Form: typeof import('./components/Form/src/Form.vue')['default']
    FormAction: typeof import('./components/Form/src/FormAction.vue')['default']
    FormItem: typeof import('./components/Form/src/FormItem.vue')['default']
    Icon: typeof import('./components/Icon/src/Icon.vue')['default']
    IconPicker: typeof import('./components/Icon/src/IconPicker.vue')['default']
    IconSvg: typeof import('./components/Icon/src/IconSvg.vue')['default']
    Markdown: typeof import('./components/Markdown/src/Markdown.vue')['default']
    PageWrapper: typeof import('./components/Page/src/PageWrapper.vue')['default']
    RadioGroup: typeof import('./components/Form/src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Form/src/components/Select.vue')['default']
    Tinymce: typeof import('./components/Tinymce/src/Tinymce.vue')['default']
    Upload: typeof import('./components/Upload/src/Upload.vue')['default']
  }
}

export {}
